[package]
name = "omasafe-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "omasafe-cli"
path = "src/main.rs"

[dependencies]
omasafe-analyzer = { path = "../omasafe-analyzer", features = ["qml-parser"] }
omasafe-core = { path = "../omasafe-core" }
omasafe-marketplace = { path = "../omasafe-marketplace" }
omasafe-plugin-trust = { path = "../omasafe-plugin-trust" }
omasafe-report = { path = "../omasafe-report" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[build-dependencies]
sha2.workspace = true

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
serde_json.workspace = true
tempfile = "3"
