[package]
name = "omasafe-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "omasafe-cli"
path = "src/main.rs"

[dependencies]
omasafe-core = { path = "../omasafe-core" }
omasafe-marketplace = { path = "../omasafe-marketplace" }
omasafe-plugin-trust = { path = "../omasafe-plugin-trust" }
omasafe-report = { path = "../omasafe-report" }
serde_json.workspace = true
